image: vladyslavusenko/b_image:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_TYPE: Release

# template for docker builds with ccache
.prepare_docker_template: &prepare_docker_definition
  tags:
    - docker
  before_script:
    - mkdir -p ccache
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache
  cache:
    key: bionic
    paths:
    - ccache/

# template for secondary build & unit test configurations
.compile_and_test_template: &compile_and_test_definition
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    - make -j4
    - ctest

# main build with benchmark and coverage
bionic-release-compile:
  <<: *prepare_docker_definition
  stage: build
  cache:
    key: bionic-release
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    - make -j4
    - ctest
    - ./test/benchmark_camera > ../benchmark_camera.txt
    - cd ../
    - mkdir build_coverage
    - cd build_coverage
    - cmake .. -DCMAKE_BUILD_TYPE=Coverage
    - make -j4
    - ctest
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '*test/*' '/usr/*' '*thirdparty*' '*googletest*' --output-file coverage.info
    - lcov --list coverage.info
  artifacts:
    paths:
    - benchmark_camera.txt

bionic-debug-compile:
  <<: *prepare_docker_definition
  <<: *compile_and_test_definition
  cache:
    key: bionic-debug
  variables:
    BUILD_TYPE: Debug

bionic-relwithdebinfo-compile:
  <<: *prepare_docker_definition
  <<: *compile_and_test_definition
  cache:
    key: bionic-relwithdebinfo
  variables:
    BUILD_TYPE: RelWithDebInfo

xenial-release-compile:
  <<: *prepare_docker_definition
  <<: *compile_and_test_definition
  image: vladyslavusenko/b_image_xenial:latest
  cache:
    key: xenial-release

elcapitan-release-compile:
  <<: *compile_and_test_definition
  tags: [macos, "10.11"]
